/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import HeroBackgroundSlot from "@/components/ui/HeroBackgroundSlot";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";
import AvatarGroup from "@/components/ui/AvatarGroup";

const primaryButton = {
  text: "Book a Call",
  href: "#contact"
};
const secondaryButton = {
  text: "Our Services",
  href: "#services"
};

type HeroBillboardProps = {
  tag?: string;
  title: string;
  description: string;
  primaryButton: { text: string; href: string };
  secondaryButton: { text: string; href: string };
  avatarsSrc?: string[];
  avatarsLabel?: string;
  textAnimation: "slide-up" | "fade-blur" | "fade";
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

const AboutInline = () => {
  return (
    <section aria-label="Error section" className="relative py-40 flex items-center justify-center min-h-[60vh] bg-[#f5f5f5]">
      <div className="bg-white rounded-lg shadow-sm border border-gray-100 p-6 max-w-[480px] w-full mx-4">
        <div className="flex justify-between items-start mb-5">
          <div className="bg-[#fdf2f2] text-[#c73a3a] text-xs font-medium px-2.5 py-1 rounded">
            Sandbox Not Found
          </div>
          <div className="bg-black text-white rounded-full flex items-center justify-center h-8 w-8">
            <svg viewBox="0 0 24 24" fill="none" className="w-5 h-5">
              <path d="M12 2L14.5 9.5L22 12L14.5 14.5L12 22L9.5 14.5L2 12L9.5 9.5L12 2Z" fill="white" />
              <circle cx="12" cy="12" r="3" fill="#f97316" />
            </svg>
          </div>
        </div>
        <p className="text-[#a04040] text-[15px] leading-relaxed">
          The sandbox <span className="text-[#c73a3a] font-bold">i2jngvrpzoua1240wf02p</span> wasn't found.
        </p>
      </div>
    </section>
  );
};

export default function AboutSection() {
  return (
    <div data-webild-section="about" data-section="about" id="about">
      <AboutInline />
    </div>
  );
}
