/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import HeroBackgroundSlot from "@/components/ui/HeroBackgroundSlot";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";
import AvatarGroup from "@/components/ui/AvatarGroup";

const primaryButton = {
  text: "Book a Call",
  href: "#contact"
};
const secondaryButton = {
  text: "Our Services",
  href: "#services"
};

type HeroBillboardProps = {
  tag?: string;
  title: string;
  description: string;
  primaryButton: { text: string; href: string };
  secondaryButton: { text: string; href: string };
  avatarsSrc?: string[];
  avatarsLabel?: string;
  textAnimation: "slide-up" | "fade-blur" | "fade";
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

const AboutInline = () => {
  return (
    <section aria-label="Our Process" className="relative pt-25 pb-20 md:pt-30">
      <div className="flex flex-col gap-12 md:gap-20 w-content-width mx-auto">
        <div className="flex flex-col gap-6 max-w-4xl">
          <div className="px-3 py-1 text-sm card rounded w-fit">
            <p>Our Process</p>
          </div>
          <TextAnimation
            text="You Show Up. We Handle The Rest."
            variant="fade-blur"
            gradientText={false}
            tag="h2"
            className="text-5xl md:text-6xl lg:text-7xl font-semibold leading-[1.15] text-foreground text-balance"
          />
          <TextAnimation
            text="No lists to chase. No bidding wars. Just homeowners who already chose you — before they ever booked."
            variant="fade-blur"
            gradientText={false}
            tag="p"
            className="text-xl md:text-2xl text-accent leading-snug text-balance max-w-3xl"
          />
        </div>

        <div className="h-px w-full bg-foreground/10" />

        <div className="flex flex-col gap-12 md:gap-16">
          <ScrollReveal variant="slide-up" delay={0.1} className="flex flex-col md:flex-row gap-4 md:gap-12 lg:gap-24">
            <div className="md:w-1/3 shrink-0">
              <h3 className="text-xl md:text-2xl font-medium text-foreground">01 — We Make You The Only Choice</h3>
            </div>
            <div className="md:w-2/3">
              <p className="text-lg md:text-xl text-accent leading-relaxed">
                Ready homeowners in your market, positioned to see you as the premium name. Never one of five bids. The one they came for.
              </p>
            </div>
          </ScrollReveal>

          <ScrollReveal variant="slide-up" delay={0.2} className="flex flex-col md:flex-row gap-4 md:gap-12 lg:gap-24">
            <div className="md:w-1/3 shrink-0">
              <h3 className="text-xl md:text-2xl font-medium text-foreground">02 — We Pre-Sell Them On You</h3>
            </div>
            <div className="md:w-2/3">
              <p className="text-lg md:text-xl text-accent leading-relaxed">
                Every follow-up, handled. They reach your calendar already knowing your name, your work, your vision. Sold before they show.
              </p>
            </div>
          </ScrollReveal>

          <ScrollReveal variant="slide-up" delay={0.3} className="flex flex-col md:flex-row gap-4 md:gap-12 lg:gap-24">
            <div className="md:w-1/3 shrink-0">
              <h3 className="text-xl md:text-2xl font-medium text-foreground">03 — You Show Up And Close</h3>
            </div>
            <div className="md:w-2/3">
              <p className="text-lg md:text-xl text-accent leading-relaxed">
                No cold-calling. No chasing. Just a homeowner who booked themselves in. Sit down and win the job.
              </p>
            </div>
          </ScrollReveal>
        </div>

        <div className="h-px w-full bg-foreground/10" />

        <ScrollReveal variant="slide-up" delay={0.4}>
          <p className="text-2xl md:text-3xl font-medium text-foreground text-balance">
            Everything before the handshake is ours. The handshake is yours.
          </p>
        </ScrollReveal>
      </div>
    </section>
  );
};

export default function AboutSection() {
  return (
    <div data-webild-section="about" data-section="about" id="about">
      <AboutInline />
    </div>
  );
}
