// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactParallaxCard from "@/components/sections/contact/ContactParallaxCard";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
              <ContactParallaxCard
                title="Get In Touch"
                imageSrc="https://storage.googleapis.com/webild/users/user_3GMBzqNQha0Ss5sANYDh3wTgZ9J/uploaded-1783784033944-okrzrj5u.png"
                inputs={[
                  { name: "name", type: "text", placeholder: "Your name" },
                  { name: "email", type: "email", placeholder: "Your email" },
                ]}
                textarea={{ name: "message", placeholder: "Tell us about your dream property...", rows: 4 }}
                buttonText="Send Message"
                footerText="Prefer to talk? Book a private tour."
                footerLink={{ text: "Email Us", href: "mailto:hello@lecercle.com", imageSrc: "https://storage.googleapis.com/webild/default/templates/marbella/contact/avatar.webp" }}
              />
            </div>
  );
}
