// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroVideoScroll from "@/components/sections/hero/HeroVideoScroll";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
              <HeroVideoScroll
                textAnimation="fade"
                videoSrc="https://storage.googleapis.com/webild/default/templates/marbella/hero/hero.mp4"
                tag="Exclusive To Your Area"
                title="#1 Growth Partner For Roofers"
                description="Exclusive homeowner appointments for established Roofing Contractors around the U.S"
                primaryButton={{ text: "View  Our Process", href: "#process" }}
                secondaryButton={{ text: "See if You Qualify", href: "#contact" }}
                bottomText="brand Konnect is designed for those seeking a unique and reliable way to acquire Quality Roofing Jobs"
              />
            </div>
  );
}
